---
title: "UPD Thesis"
author: "Terry Kim"
date: "2023-04-05"
output:
  pdf_document: default
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

rm(list=ls()) # removes all objects from the environment

cat('\014') # clears the console

```


```{r, include=FALSE}

if (!require(haven)) install.packages("haven"); library(haven)

if (!require(sandwich)) install.packages("sandwich"); library(sandwich)

if (!require(lmtest)) install.packages("lmtest"); library(lmtest)

if (!require(stargazer)) install.packages("stargazer"); library(stargazer)

if (!require(ggplot2)) install.packages("ggplot2"); library(ggplot2)

if (!require(statar)) install.packages("statar"); library(statar)

if (!require(msm)) install.packages("msm"); library(msm)

if (!require(foreign)) install.packages("foreign"); library(foreign)

if (!require(car)) install.packages("car"); library(car)

if (!require(gplots)) install.packages("gplots"); library(gplots)

if (!require(plm)) install.packages("plm"); library(plm)

if (!require(lfe)) install.packages("lfe"); library(lfe)

```


```{r}

data = read.csv("data_clean.csv")

plotmeans(log(rent) ~ district, main = "Heterogeneity across districts", data=data)

plotmeans(log(rent) ~ year, main = "Heterogeneity across years", data=data)

```


## average rent vs. airbnb density at current year's listings and population (t)

```{r}

eq1 = felm(log(rent) ~ adp_now | factor(district) | 0 | district, data = data)

summary(eq1)$coefficients


eq2 = felm(log(rent) ~ adp_now | factor(year) | 0 | year, data = data)

summary(eq2)$coefficients


eq3 = felm(log(rent) ~ adp_now | factor(year) + factor(district) | 0 | district + year, data = data)

summary(eq3)$coefficients

```

## average rent vs. airbnb density at previous year's listings and population (t-1)

```{r}

eq4 = felm(log(rent) ~ adp_prev | factor(district) | 0 | district, data = data)

summary(eq4)$coefficients


eq5 = felm(log(rent) ~ adp_prev | factor(year) | 0 | year, data = data)

summary(eq5)$coefficients


eq6 = felm(log(rent) ~ adp_prev | factor(year) + factor(district) | 0 | district + year, data = data)

summary(eq6)$coefficients

```


## average rent vs. airbnb density at the listings and population two years ago (t-2)

```{r}

eq7 = felm(log(rent) ~ adp_2yr_ago | factor(district) | 0 | district, data = data)

summary(eq7)$coefficients


eq8 = felm(log(rent) ~ adp_2yr_ago | factor(year) | 0 | year, data = data)

summary(eq8)$coefficients


eq9 = felm(log(rent) ~ adp_2yr_ago | factor(year) + factor(district) | 0 | district + year, data = data)

summary(eq9)$coefficients

```
